on: [push]

name: Container CI/CD

jobs:
  build-image:
    runs-on: ubuntu-latest
    environment: demo
    strategy:
      matrix:
        java: [ '17' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2    

    - name: Login to the Container Registry  
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v2
      with:
        java-version: ${{matrix.java}}
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.ACR_LOGIN_SERVER }}/spring-petclinic:${{ github.run_number }}

    - name: Scan image
      if: ${{ vars.SCAN_ENABLED == 'true' }}
      uses: Azure/container-scan@v0
      with:
        image-name: ${{ secrets.ACR_LOGIN_SERVER }}/spring-petclinic:${{ github.run_number }}
        severity-threshold: CRITICAL
        run-quality-checks: true

    - name: Push image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/spring-petclinic:${{ github.run_number }}